# -*- coding: utf-8 -*-
"""Enkripsi XOR dan Steganografi LSB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IABlb3HRyS3L2XiUyiQ6A3s33h0lgEzw

# Enkripsi Citra dengan XOR
"""

# Install library untuk membuka dan memanipulasi citra
!pip install pillow

from PIL import Image
import numpy as np

# Fungsi untuk mengenkripsi citra menggunakan XOR
def encrypt_image(image_path, key):
    # Membuka gambar
    img = Image.open(image_path)
    img_array = np.array(img)

    # Mengenkripsi gambar menggunakan operasi XOR
    encrypted_img_array = np.bitwise_xor(img_array, key)

    # Mengubah array menjadi gambar kembali
    encrypted_img = Image.fromarray(encrypted_img_array)

    # Menyimpan citra yang telah terenkripsi
    encrypted_img.save('encrypted_image.png')
    encrypted_img.show()

# Fungsi untuk mendekripsi citra yang dienkripsi menggunakan XOR
def decrypt_image(encrypted_image_path, key):
    # Membuka gambar terenkripsi
    img = Image.open(encrypted_image_path)
    img_array = np.array(img)

    # Mendekripsi gambar menggunakan operasi XOR
    decrypted_img_array = np.bitwise_xor(img_array, key)

    # Mengubah array menjadi gambar kembali
    decrypted_img = Image.fromarray(decrypted_img_array)

    # Menyimpan citra yang telah didekripsi
    decrypted_img.save('decrypted_image.png')
    decrypted_img.show()

# Path gambar yang akan dienkripsi
image_path = 'Cctv.jpg'  # Gantilah dengan path gambar Anda

# Membuat key untuk XOR
key = 123  # Angka ini dapat diubah sesuai keinginan

# Mengenkripsi dan mendekripsi gambar
encrypt_image(image_path, key)
decrypt_image('encrypted_image.png', key)

"""# Steganografi LSB"""

# Fungsi untuk menyisipkan pesan dalam citra
def encode_message(image_path, message, output_image_path):
    # Membuka gambar
    img = Image.open(image_path)
    img_array = np.array(img)

    # Mengonversi pesan menjadi binary
    binary_message = ''.join(format(ord(i), '08b') for i in message)

    # Menyisipkan pesan ke dalam citra (Least Significant Bit)
    data_index = 0
    for i in range(img_array.shape[0]):
        for j in range(img_array.shape[1]):
            for k in range(3):  # Untuk setiap kanal warna (RGB)
                if data_index < len(binary_message):
                    img_array[i][j][k] = (img_array[i][j][k] & 0xFE) | int(binary_message[data_index])
                    data_index += 1

    # Menyimpan citra hasil steganografi
    encoded_img = Image.fromarray(img_array)
    encoded_img.save(output_image_path)
    encoded_img.show()

# Fungsi untuk mengekstrak pesan dari citra yang telah disisipi
def decode_message(encoded_image_path):
    # Membuka gambar yang telah disisipi pesan
    img = Image.open(encoded_image_path)
    img_array = np.array(img)

    # Menyusun binary message dari LSB
    binary_message = ''
    for i in range(img_array.shape[0]):
        for j in range(img_array.shape[1]):
            for k in range(3):  # Untuk setiap kanal warna (RGB)
                binary_message += str(img_array[i][j][k] & 1)

    # Mengonversi binary message ke dalam teks
    decoded_message = ''
    for i in range(0, len(binary_message), 8):
        byte = binary_message[i:i+8]
        decoded_message += chr(int(byte, 2))

    return decoded_message

# Path gambar untuk steganografi
image_path = 'Cctv.jpg'  # Gantilah dengan path gambar Anda
message = "Ini adalah pesan rahasia!"

# Menyisipkan pesan ke dalam citra
encode_message(image_path, message, 'stego_image.png')

# Mengekstrak pesan dari citra yang telah disisipi
decoded_message = decode_message('stego_image.png')
print("Pesan yang diekstrak:", decoded_message)